name: brick_ditto
description: Ditto Live synchronization adapter for Brick Offline First.
version: 1.0.0
homepage: https://github.com/yegobox/flipper

environment:
  sdk: ^3.5.3
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  brick_core: any
  ditto_live: ^4.13.0
  meta: ^1.16.0

dev_dependencies:
  brick_build: ^4.0.0
  build_runner: ^2.4.15
  test: ^1.25.0