name: brick_ditto
description: Ditto Live synchronization adapter for Brick Offline First.
version: 1.0.0
homepage: https://github.com/yegobox/flipper

environment:
  sdk: ^3.5.3
  flutter: ">=3.3.0"

dependencies:
  brick_core:
    path: ../brick_core
  ditto_live: ^4.13.1
  flutter:
    sdk: flutter
  meta: ^1.16.0

dev_dependencies:
  brick_build:  any
  build_runner: ^2.4.15
  test: ^1.25.0