name: supabase_models
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  brick_offline_first_with_supabase: ^2.0.0
  brick_sqlite: ^4.0.1
  brick_supabase: ^2.0.1
  supabase_flutter: ^2.12.0
  sqflite_common: ^2.5.4+6 
  sqflite_common_ffi: ^2.4.0+1
  path_provider: ^2.1.5
  path: ^1.9.0
  uuid: ^4.5.1
  http: ^1.3.0
  mock_supabase_http_client: 0.0.3+1
  mockito: ^5.4.5
  brick_offline_first: ^4.0.0
  sqflite_common_ffi_web: ^1.0.1+1
  flipper_models: any
  flipper_services: any
  sqlite3: ^3.1.3
  ditto_live: ^4.14.0
  flipper_web: any
  brick_ditto_generators: any
dependency_overrides:
  device_info_plus: ^12.3.0
  sqlite3: ^3.1.3
  archive: ^3.6.1
  excel: ^4.0.6
  cbor: ^6.3.7
  jni: ^0.14.2
  meta: ^1.16.0
  source_gen: ">=3.0.0 <5.0.0"


flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  brick_sqlite_generators: ^4.0.0
  brick_offline_first_with_supabase_build: ^2.0.0
  build_runner: ^2.4.15
  source_gen: ">=3.0.0 <5.0.0"
