name: flipper_services
description: flipper models scaffold.
version: 1.0.0-dev

repository: https://github.com/yegobox/packages



dependencies:
  flutter:
    sdk: flutter

  stacked: ^3.5.0
  firebase_remote_config: ^6.0.0
  share_plus: ^10.1.4
  firebase_messaging: ^16.1.0
  image: ^4.5.4
  firebase_auth: ^6.1.0
  geolocator: ^13.0.2
  geocode: ^1.0.3
  firebase_analytics: ^12.0.2
  firebase_crashlytics: ^5.0.2
  location: ^8.0.0
  google_sign_in: ^6.2.2
  dio: ^5.4.3+1
  http: ^1.2.2
  intl: ^0.20.2
  path_provider: ^2.1.5
  path: ^1.8.2
  googleapis: ^11.2.0
  timeago: ^3.4.0
  
  stacked_services: ^1.6.0
  universal_platform: ^1.0.0+1
  googleapis_auth: ^1.4.1
  timezone: ^0.10.0
  connectivity_plus: ^7.0.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  flipper_routing: ^1.0.0
  flipper_models: any
  flipper_web: any

  google_fonts: ^6.1.0
  shared_preferences: ^2.5.2
  # newrelic_mobile: ^1.1.12
  flutter_local_notifications: ^19.5.0
 
  window_manager: ^0.4.0
  launcher_entry: ^0.1.1
  internet_connection_checker: ^1.0.0+1
  talker_flutter: ^4.1.5
  supabase_flutter: ^2.12.0
  firebase_core: ^4.2.1
  # cbl_flutter_ce: ^3.1.3
  # cbl_flutter: ^3.1.3
  supabase_models: any
  file_picker: ^10.3.7
  url_launcher: ^6.3.1
  # flipper_rw: any
  device_info_plus: ^12.3.0
dependency_overrides:
  http: ^1.2.2
  meta: ^1.16.0
  web: ^1.0.0
  json_annotation: ^4.9.0
  sqlite3: ^3.1.3
  package_info_plus: ^9.0.0
  device_info_plus: ^12.3.0
  archive: ^3.6.1
  excel: ^4.0.6
  cbor: ^6.3.7
  jni: ^0.14.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.0
  build_runner: ^2.4.15
  test:
  mocktail: ^1.0.4
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/flipper.pem
