name: brick_sqlite_generators
description: Code generation library for the SQLite providers, models, and adapters in Brick
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_sqlite_generators
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 4.0.1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  analyzer: ">=6.11.0 <9.0.0"
  brick_build:
    path: ../brick_build
  brick_core:
    path: ../brick_core
  brick_sqlite:
    path: ../brick_sqlite
  build: ">=2.4.2 <2.5.0"
  dart_style: ">=3.0.0 <4.0.0"
  meta: ">=1.3.0 <2.0.0"
  source_gen: ^2.0.0

dev_dependencies:
  brick_build_test:
    path: ../brick_build_test
  lints:
  test:
