name: flipper_accounting
description: A new Flutter package.
version: 0.0.1
# homepage: 

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.5.0
  flipper_models: any
  flipper_services: any
  intl: ^0.20.2


dependency_overrides:
  http: ^1.2.2
  meta: ^1.16.0
  web: ^1.0.0
  json_annotation: ^4.9.0
  sqlite3: ^3.1.3
  device_info_plus: ^12.3.0
  archive: ^3.6.1
  cbor: ^6.3.7
  jni: ^0.14.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0
  # stacked_generator: ^1.3.0
  # build_runner: ^2.4.6

