name: flipper_models
description: flipper models scaffold.
version: 0.0.1-dev.7
repository: https://github.com/yegobox/packages

environment:
  sdk: '>=3.10.4 <4.0.0'



dependencies:
  df_safer_dart: ^0.17.8
  equatable: ^2.0.3
  
  meta: ^1.3.0
  universal_platform: ^1.0.0+1
  stacked_services: ^1.6.0
  firebase_auth: ^6.1.0
  stacked: ^3.5.0
  built_value: ^8.1.4
  azlistview: ^2.0.0
  scrollable_positioned_list: ^0.3.2-dev
  built_collection: ^5.1.1
  flipper_services: any
  flipper_routing: ^1.0.0
  connectivity_plus: ^7.0.0
  
  sentry: ^9.8.0
  sentry_flutter: 9.8.0
  
  path_provider: ^2.1.5
  http: ^1.2.2
  html_unescape: ^2.0.0
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  flutter_hooks: ^0.21.0
  riverpod: ^3.0.3
  hooks_riverpod: ^3.0.3
  freezed_annotation: any
  dart_mappable: ^4.2.1
  dio: ^5.4.3+1
  talker_dio_logger: ^4.1.5
  talker: ^4.1.5
  talker_flutter: ^4.1.5
  rxdart: ^0.28.0
  collection: ^1.19.0
  intl: ^0.20.2
  amplify_core: ^2.7.0
  amplify_api: ^2.7.0
  amplify_flutter: ^2.7.0
  amplify_auth_cognito: ^2.7.0
  amplify_storage_s3: ^2.7.0
  async: ^2.11.0
  archive: ^3.6.1
  mime: ^2.0.0
  firebase_core: ^4.2.1
  # sqlite3_flutter_libs: ^0.5.40
  sqlite3: ^3.1.3
  permission_handler: ^12.0.1
  json_annotation: ^4.9.0
  supabase_flutter: ^2.12.0
  supabase_models: any
  printing: ^5.14.2
  pdf: ^3.11.3
  injectfy: ^1.0.1
  mock_supabase_http_client: 0.0.3+1
  # sqlite3_web: '>=0.2.1 <0.4.0'
  synchronized: ^3.3.0+3
  email_validator: ^2.1.17
  faker: ^2.2.0
  flipper_personal: any
  flipper_web: any
  

dependency_overrides:
  http: ^1.2.2
  meta: ^1.16.0
  jni: ^0.14.2
  web: ^1.0.0
  json_annotation: ^4.9.0
  sqlite3: ^3.1.3
  stacked_services: ^1.6.0
  device_info_plus: ^12.3.0
  archive: ^3.6.1
  excel: ^4.0.6
  mime: ^2.0.0
  cbor: ^6.3.7
  
  
dev_dependencies:
  build_runner: ^2.4.15
  dart_mappable_builder: ^4.4.0
  json_serializable: ^6.9.4
  # cloud_firestore_odm_generator: ^1.0.0-dev.89
  mocktail: ^1.0.4
  riverpod_generator: ^3.0.0  # Updated to support riverpod_annotation ^3.0.3
  riverpod_lint: ^3.0.3  # Updated to be compatible with riverpod ^3.0.3
  test: ^1.26.2
  # cloud_firestore_odm_generator: ^1.0.0-dev.88
flutter:
  uses-material-design: true
  assets:
    - jsons/