name: flipper_web
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+906

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  riverpod: ^3.0.3
  http: ^1.2.1
  supabase_flutter: ^2.12.0
  cupertino_icons: ^1.0.8
  sqflite_common_ffi_web: ^1.0.1+1
  flipper_ui: ^1.0.3
  flutter_localizations:
    sdk: flutter
  go_router: ^16.2.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  firebase_auth: ^6.1.0
  firebase_core: ^4.3.0
  ditto_live: ^4.14.2
  permission_handler: ^12.0.1
  wolt_modal_sheet: 0.11.0
  google_fonts: ^6.2.1
  path: ^1.9.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  riverpod_annotation: ^3.0.3
  sqflite_common: ^2.5.4+6
dependency_overrides:
  archive: ^3.6.1
  sqlite3: ^3.1.3

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  riverpod_generator: ^3.0.3
  build_runner: ^2.10.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
