name: flipper_login
description: >
  flipper models scaffold.
version: 0.0.1-dev.5
repository: https://github.com/yegobox/packages

# publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  firebase_ui_auth: ^3.0.0
  flutter_form_bloc: 0.31.0-dev
  firebase_core: ^4.2.1
  flipper_services: any
  flipper_dashboard: any
  universal_platform: ^1.0.0+1
  country_code_picker: ^3.0.0
  overlay_support: ^2.1.0
  flutter_settings_ui: ^3.0.1
  stacked: ^3.5.0
  google_fonts: ^6.1.0
  firebase_auth: ^6.1.0
  flipper_routing: ^1.0.0
  connectivity_plus: ^7.0.0
  firebase_ui_localizations: ^2.0.0
  firebase_ui_oauth: ^2.0.0
  firebase_ui_oauth_google: ^2.0.0
  flutter_svg: ^2.0.0
  gap: ^2.0.0
  qr_flutter: ^4.1.0
  flipper_ui: ^1.0.3
  flipper_socials: 1.0.0+1
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  flutter_hooks:
  riverpod: ^3.0.3
  hooks_riverpod: ^3.0.3
  loading_animation_widget: ^1.2.0+4
  sentry: ^9.8.0
  sentry_flutter: 9.8.0
  flipper_models: any
  google_sign_in: ^6.2.2
  firebase_ui_oauth_apple: ^2.0.0
  pin_code_fields: ^8.0.1
  sign_in_with_apple: ^7.0.1
  
dependency_overrides:
  google_sign_in: ^6.2.2
  http: ^1.2.2
  meta: ^1.11.0
  web: ^1.0.0
  json_annotation: ^4.9.0
  sqlite3: ^3.1.1
  device_info_plus: ^12.3.0
  archive: ^3.6.1
  excel: ^4.0.6
  cbor: ^6.3.7
  jni: ^0.14.2
  

flutter:
  assets:
    - assets/
    - google_fonts/
